version: "3"
services:
  redis1:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data1:/data
  redis2:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data2:/data

volumes:
  redis_data1:
  redis_data2:
